---
title: "Ch4.4_20200429"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.4 Relational Operators

這節在介紹產生「要/不要」向量的常見手法。

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

### 比較

`>`,`<`,`<=`,`>=`: 分別為大於、小於、小於等於、大於等於

 * 數字比較

 * 時間比較

 * 可排序類別資料比較
 
 
##### 數字比較{-}

###### example裡誰的身高大於等於170{-}

```{r}
example$name[c(T, F, T, F)]
```

```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```



###### 不同屆入學學生在2年級的學業表現

```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
```

```{r}
str(transcript100to103)
```

分析情境：
```{r}
# 各學屆2年級人數
table(transcript100to103$學屆)
# 各學屆2年級成績大於85人數
table(transcript100to103$學屆[pick_above85])
```

選成績大於85分
```{r}
# 只要成績大於85的
pick_above85 <-
  transcript100to103$`成績` > 85
```

```{r}
# 各學屆2年級人數
table(transcript100to103$學屆)
# 各學屆2年級成績大於85人數
table(transcript100to103$學屆[pick_above85])
```



##### 時間比較: {-}

###### example裡誰1998年(含)以後出生{-}

```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
```

```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```


###### 美元匯率{-}

```{r}
source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")
```

```{r}
str(exchangeRate)
```


情境：
```{r}
exchangeRate_after98 <-
  list(
    `期間`=exchangeRate$`期間`[pick_after98_01],
    `幣別`=exchangeRate$`幣別`[pick_after98_01],
    `匯率`=exchangeRate$`匯率`[pick_after98_01]
    
  )
```

##### 選1998年1月(含)以後的匯率
```{r}
# 只要1998年1月（含）以後的
library(lubridate)
pick_after98_01 <-
  exchangeRate$期間 >= ymd("1998-01-01")
```

###### 選出1998年1月(含)以後的匯率資料

```{r}
exchangeRate_after98 <-
  list(
    `期間`=exchangeRate$`期間`[pick_after98_01],
    `幣別`=exchangeRate$`幣別`[pick_after98_01],
    `匯率`=exchangeRate$`匯率`[pick_after98_01]
  )
```


